spring:
  data:
    redis:
      host: redis-dtbroker-dev.westus2.redisenterprise.cache.azure.net
      password: ${redisAccessKey}
      port: ${REDIS_CONTAINER_PORT:10000}
      ssl:
        enabled: true
  cloud:
    azure:
      keyvault:
        secret:
          property-sources:
            - endpoint: https://kv-db-wu2-d.vault.azure.net/
              credential:
                azure-cli-enabled: true
  jpa:
    properties:
      hibernate:
        dialect: com.eds.dtbroker.sync.model.EmptyDialect
  datasource:
    driver-class-name: "net.snowflake.client.jdbc.SnowflakeDriver"
    url: "jdbc:snowflake://${snowflake.account}.snowflakecomputing.com/?warehouse=${snowflake.warehouse}&db=${snowflake.db}&schema=${snowflake.schema}&role=${snowflake.role}&TIMEZONE=UTC&CLIENT_RESULT_COLUMN_CASE_INSENSITIVE=true&CLIENT_TIMESTAMP_TYPE_MAPPING=TIMESTAMP_NTZ&JDBC_QUERY_RESULT_FORMAT=json"

snowflake:
  account: "lithia.west-us-2.azure"
  warehouse: "EDS_DEV_UAT_WH"
  db: "${SNOWFLAKE_DB_NAME:DI_DEV}"
  schema: "${SNOWFLAKE_SCHEMA:CORE}"
  role: "A_MKTG_SNOWFLAKE_DEV_DEVELOPER"
  user: "s_databroker_non_prod"
  private-key-name: "snowflakePrivateKey"
  private-key-password: "snowflakePrivateKeyPassword"

logging:
  level:
    com.azure: DEBUG
    com.microsoft: DEBUG
    org.springframework.data.redis: DEBUG
    io.lettuce.core: DEBUG