spring:
  data:
    redis:
      host: 127.0.0.1
      password: ""
      port: 6379
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: root
    password: toor
    driver-class-name: org.postgresql.Driver
