snowflake:
  account: "lithia.west-us-2.azure"
  warehouse: "EDS_DEV_UAT_WH"
  db: "DI_DEV"
  schema: "CORE"
  role: "A_MKTG_SNOWFLAKE_DEV_DEVELOPER"

spring:
  data:
    redis:
      host: redis-dtbroker-dev.westus2.redisenterprise.cache.azure.net
      password: ${REDIS_ACCESS_KEY}
      port: ${REDIS_CONTAINER_PORT:10000}
      ssl:
        enabled: true
  jpa:
    properties:
      hibernate:
        dialect: com.eds.dtbroker.sync.model.EmptyDialect
  datasource:
    username: "s_databroker_non_prod"
    driver-class-name: "net.snowflake.client.jdbc.SnowflakeDriver"
    private-key-path: "<fetch from vault>"
    private-key-password: "<fetch from vault>"
    url: "jdbc:snowflake://${snowflake.account}.snowflakecomputing.com/?warehouse=${snowflake.warehouse}&db=${snowflake.db}&schema=${snowflake.schema}&role=${snowflake.role}&TIMEZONE=UTC&CLIENT_RESULT_COLUMN_CASE_INSENSITIVE=true&CLIENT_TIMESTAMP_TYPE_MAPPING=TIMESTAMP_NTZ&JDBC_QUERY_RESULT_FORMAT=json"